[build]
# Directory to run the build command in
base = "typescript"

# Build command to run
command = "bun run build"

# Directory with the static files to deploy
publish = "apps/web/dist"

[build.environment]
# Use Node.js 18 or higher
NODE_VERSION = "18"

[[redirects]]
from = "/success"
to = "/success"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-ancestors 'none';"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.svg"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/*.jpg"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "public, max-age=86400"

[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true


